export default interface SocialMediaItem {
    url: string;
    optionalName?: string;
    socialMediaType:
    | "Facebook"
    | "Instagram"
    | "Website"
    | "Telegram"
    | "Dribbble"
    | "Github"
    | "Bēhance"
    | "Youtube"
    | "Discord"
    | "Twitch"
    | "Spotify"
    | "LinkedIn"
    | "Binance"
    | "Snapchat"
    | "FacebookMessenger"
    | "Slack"
    | "Tinder"
    | "Soundcloud"
    | "Airbnb"
    | "Tik Tok"
    | "GoogleMaps"
    | "Waze"
    | "Other"
    | "Phone"
    | "Mail"
    | "TikTok"
    | "Paypal"
    | "WhatsApp"
    | "Pinterest"
    | "X";
}
